[package]
name = "native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "native"
crate-type = ["staticlib","cdylib"]

[dependencies]
anyhow = "1"
flutter_rust_bridge = "1"
buttplug = "7.0.1"